### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by cseanburns** [tawnjovi/ICT_420_Spring#1]
Some things to address:

- remove all CSS
- `<head>` should come immediately after `<html>`. But also, remove `<style>` and all CSS
- add an `alt="text description here"` for all `<img>` elements
- the `</body>` goes right before the closing `</html>` tag at the very bottom of the page

After making these fixes, see if you catch any other errors at https://html5.validator.nu/

**Comment by tawnjovi** [comment]
Thank you Dr. Burns,

I just revised the file and will look for more errors.
